##########################################################################################
##
##  usto stuff for m5-identify ...
##
##########################################################################################

##########################################################################################
##
##  Info to display ............. by usto
##
##########################################################################################



input_select:
  m5_identify_color:
    name: Ident-Farbe
    options:
      - use_local
      - "Red"
      - "Orange"
      - "Amber"
      - "Yellow"
      - "Lime"
      - "Green"
      - "Mint"
      - "Cyan"
      - "Sky"
      - "Blue"
      - "Indigo"
      - "Violet"
      - "Purple"
      - "Magenta"
      - "Pink"
      - "Rose"
      - "Brown"
      - "Grey"
      - "White"
    initial: use_local
    icon: mdi:palette

  m5_ident_pattern:
    name: Blinkmuster
    options:
      - Kurz (200ms)
      - Standard (300ms)
      - Lang (500ms)
      - Nur 1x
    initial: Standard (300ms)
    icon: mdi:animation

input_boolean:
  identify_all_devices:
    name: Identifizierung aktivieren
    icon: mdi:radar
    initial: true       # Startet standardmäßig auf "on"


  m5_ident_disable_local:
    name: Lokales Blinken deaktivieren
    icon: mdi:flash-off

  m5_ident_enable_local:
    name: Lokales Blinken aktivieren
    icon: mdi:flash

  identity_alive_home_status:
    name: "Identity Alive Home Status"
    icon: mdi:home-account

input_button:
  m5_ident_trigger:
    name: Synchrones Blinken starten
    icon: mdi:led-on



automation:
  - id: sync_identity_alive_home_status
    alias: "Sync Identity Alive Home Status mit person.thomas (core_esp_m5_identify_helper)"
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.person_first
    action:
      - service: >
          {% if is_state('binary_sensor.person_first', 'on') %}
            input_boolean.turn_off
          {% else %}
            input_boolean.turn_on
          {% endif %}
        target:
          entity_id: input_boolean.identity_alive_home_status

                  

  - id: trigger_identify_script_all_esphome_synchron
    alias: "Trigger identify script on all ESPHome devices synchrone automation (core_esp_m5_identify_helper)"
    mode: queued
    initial_state: true   # 👈 DAS deaktiviert die Automation beim Start    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # initial_state: false   # 👈 DAS deaktiviert die Automation beim Start
    trigger:
      - platform: time_pattern
        minutes: "/5"

    condition:
    condition:
      - condition: state
        entity_id: input_boolean.identify_all_devices
        state: "on"

      # Neue kombinierte Bedingung:
      - condition: or
        conditions:
          # Fall 1: Nicht zu Hause → immer ausführen
          - condition: state
            entity_id: input_boolean.identity_alive_home_status
            state: "on"

          # Fall 2: Zu Hause → nur wenn Sonne höher als -5°
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.identity_alive_home_status
                state: "off"
              - condition: numeric_state
                entity_id: sun.sun
                attribute: elevation
                above: -5
    action:
      - service: script.trigger_identify_script_all_esphome_synchron


script:
  trigger_identify_script_all_esphome_synchron:
    alias: "Trigger identify script on all ESPHome devices synchrone script (core_esp_m5_identify_helper)"
    mode: single

    sequence:
      # --------------------------------------------------
      # Gemeinsame Variablen
      # --------------------------------------------------
      - variables:
          red: "{{ (255 / 23 * now().hour) | round(0, 'floor') | int }}"
          green: "{{ (255 / 59 * now().minute) | round(0, 'floor') | int }}"
          blue: "{{ (255 / 59 * now().second) | round(0, 'floor') | int }}"

          brightness: >
            {% if state_attr('sun.sun', 'elevation') > 0 %}
              100
            {% elif is_state('input_boolean.identity_alive_home_status', 'off') %}
              20
            {% else %}
              100
            {% endif %}

          repcount: 4
          on_ms: 500
          off_ms: 250
          delay_step: 2
          entity_list: >
            {{ states.switch
              | selectattr('entity_id', 'search', '_identify_active$')
              | map(attribute='entity_id')
              | map('replace', 'switch.', '')
              | map('replace', '_identify_active', '')
              | list }}

            
      # --------------------------------------------------
      # Über alle ESPHome Devices iterieren
      # --------------------------------------------------
      - repeat:
          for_each: "{{ entity_list }}"
          sequence:
            - variables:
                index_from_end: "{{ (entity_list | count - 1) - repeat.index + 1 }}"

            - service: >
                esphome.{{ repeat.item }}_check_identify_state
              continue_on_error: true
              data:
                r: "{{ red }}"
                g: "{{ green }}"
                b: "{{ blue }}"
                brightness: "{{ brightness }}"
                repeat: "{{ repcount }}"
                on_ms: "{{ on_ms }}"
                off_ms: "{{ off_ms }}"
                start_delay: "{{ delay_step * index_from_end }}"








